version: '3'
services:
  web-app:
    build: web-app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web-app/src:/web-app/src"
    depends_on: 
      - "db"
      - "db_redis"
      - "db_postgres"
  db:
    build: db
    ports: 
     - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=test123"
      - "MYSQL_DATABASE=web-app"
  db_redis:
    build: db_redis
    command: redis-server --requirepass test123
    ports: 
      - "6379:6379"
  db_postgres:
    build: db_postgres
    ports: 
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: root
      POSTGRES_DB: web-app
  nginx:
    build: nginx
    volumes:
      - "./nginx/spa:/usr/share/nginx/html/"
    ports:
      - "8888:80"
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80